name: 'Nightly Merge'

on:
  push:
    branches:
      - develop

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
#    - name: Nightly Merge
#      uses: robotology/gh-action-nightly-merge@v1.3.1
#      with:
#        stable_branch: 'develop'
#        development_branch: 'main'
#        allow_ff: true
#        ff_only: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Manual Merge
      run: |
        git checkout main
        echo
        echo "  'Nightly Merge Action' is trying to merge the 'develop' branch ($(git log -1 --pretty=%H develop))"
        echo "  into the 'main' branch ($(git log -1 --pretty=%H main))"
        echo
        git merge --ff-only --no-edit develop
        git push origin main
